[Desktop] Add store and new algorithm pages
aobolensk/webforces pull request #112
Opened 2020-12-20 18:01 UTC by adudchen

2020-12-20 18:18 UTC, aobolensk requested changes

2020-12-20 18:18 UTC, aobolensk commented on webforces/server/structs.py
> +    alg_id: int = -1
This is done intentionally. You should provide an ID. If you don't have any just use 0.

2020-12-20 18:18 UTC, aobolensk commented on webforces/server/mongodbworker.py
> +                logger.debug("This algorithm does not exist")
Why do we need to replace it?

2020-12-20 18:18 UTC, aobolensk commented on webforces/api/views.py
> +        if request.data['fromTitle'] == '1':
What does `fromTitle` param mean? We already have separate view for getting algs using title. See `class AlgViewTitle` in current file.

2020-12-20 18:18 UTC, aobolensk commented on desktop_app/GUI/UI/MainWindow.ui
> -    <width>906</width>
Do we actually need changes related to size in this file?

2020-12-20 18:18 UTC, aobolensk commented on desktop_app/GUI/Py/MainWindow.py
> -        MainWindow.resize(906, 720)
Do we actually need changes related to size in this file?

2020-12-20 18:18 UTC, aobolensk commented on desktop_app/GUI/Py/MainWindow.py
> +        self.storeButton = QtWidgets.QPushButton(self.widget1)
Why widget1?

2020-12-20 18:18 UTC, aobolensk commented on desktop_app/GUI/Py/ui.py
> +        elif langText == "C++":
lang_id == unknown language. See: `structs.py`

2020-12-21 11:58 UTC, adudchen commented
![image](https://user-images.githubusercontent.com/43030865/102774883-e2905100-439c-11eb-8a1e-aa664a0b5e76.png)
Я отказываюсь не ресайзить MainWindow

2020-12-21 12:14 UTC, aobolensk commented on webforces/api/views.py
> +        print(data['login'])
Remove this debug print, please

2020-12-21 12:16 UTC, aobolensk approved these changes

2020-12-21 13:09 UTC, skonnov approved these changes

2020-12-21 13:09 UTC, merged