[Backend] Add runners dispatching in core and basic scheduling test
aobolensk/webforces pull request #93
Opened 2020-12-15 17:43 UTC by aobolensk

close #89

2020-12-19 13:18 UTC, left841 approved these changes, later dismissed

2020-12-20 09:22 UTC, skonnov requested changes

2020-12-20 09:22 UTC, skonnov commented on webforces/server/runners/tests.py
> +        user1 = User(0, "LOGIN_USER1", "FN_USER1", "SN_USER1", "MN_USER1", [])
please add  new User field

2020-12-20 09:22 UTC, skonnov commented on webforces/server/runners/tests.py
> +        alg1 = Algorithm(0, "TITLE_ALG1", user1.user_id, "SOURCE_ALG1", [], Language.lang_cpp)
please add new Algorithm fields

2020-12-20 09:28 UTC, aobolensk commented on webforces/server/runners/tests.py
> +        user1 = User(0, "LOGIN_USER1", "FN_USER1", "SN_USER1", "MN_USER1", [])
Done

2020-12-20 09:28 UTC, aobolensk commented on webforces/server/runners/tests.py
> +        alg1 = Algorithm(0, "TITLE_ALG1", user1.user_id, "SOURCE_ALG1", [], Language.lang_cpp)
Done

2020-12-20 10:04 UTC, skonnov approved these changes

2020-12-20 16:05 UTC, megarungle approved these changes

2020-12-20 16:05 UTC, merged