[CI] Enable Selenium tests launch
aobolensk/webforces pull request #98
Opened 2020-12-18 17:24 UTC by aobolensk

2020-12-18 17:29 UTC, skonnov approved these changes, later dismissed

2020-12-19 12:20 UTC, left841 requested changes
You need to add users to pass selenium tests. See new requirements: https://github.com/aobolensk/webforces/pull/100/files

2020-12-19 12:42 UTC, aobolensk commented
> You need to add users to pass selenium tests. See new requirements: https://github.com/aobolensk/webforces/pull/100/files

Done.

2020-12-19 12:43 UTC, left841 approved these changes

2020-12-19 12:44 UTC, skonnov approved these changes

2020-12-19 12:44 UTC, merged